import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faDeleteLeft,
  faAngleUp,
  faAngleDown,
} from "@fortawesome/free-solid-svg-icons";
const iconSize = "lg";

// explore usng toLowerCase()

export let DesktopKeys = [
  {
    id: "Desktop-One",
    click: "addCharacter",
    lowerValue: "1",
    lowerRender: "1",
    upperValue: "!",
    UpperRender: "!",
  },
  {
    id: "Desktop-Two",
    click: "addCharacter",
    lowerValue: "2",
    lowerRender: "2",
    upperValue: '"',
    UpperRender: '"',
  },
  {
    id: "Desktop-Three",
    click: "addCharacter",
    lowerValue: "3",
    lowerRender: "3",
    upperValue: "£",
    UpperRender: "£",
  },
  {
    id: "Desktop-Four",
    click: "addCharacter",
    lowerValue: "4",
    lowerRender: "4",
    upperValue: "$",
    UpperRender: "$",
  },
  {
    id: "Desktop-Five",
    click: "addCharacter",
    lowerValue: "5",
    lowerRender: "5",
    upperValue: "%",
    UpperRender: "%",
  },
  {
    id: "Desktop-Six",
    click: "addCharacter",
    lowerValue: "6",
    lowerRender: "6",
    upperValue: "^",
    UpperRender: "^",
  },
  {
    id: "Desktop-Seven",
    click: "addCharacter",
    lowerValue: "7",
    lowerRender: "7",
    upperValue: "&",
    UpperRender: "&",
  },
  {
    id: "Desktop-Eight",
    click: "addCharacter",
    lowerValue: "8",
    lowerRender: "8",
    upperValue: "*",
    UpperRender: "*",
  },
  {
    id: "Desktop-Nine",
    click: "addCharacter",
    lowerValue: "9",
    lowerRender: "9",
    upperValue: "(",
    UpperRender: "(",
  },
  {
    id: "Desktop-Zero",
    click: "addCharacter",
    lowerValue: "0",
    lowerRender: "0",
    upperValue: ")",
    UpperRender: ")",
  },
  {
    id: "Desktop-Minus",
    click: "addCharacter",
    lowerValue: "-",
    lowerRender: "-",
    upperValue: "_",
    UpperRender: "_",
  },
  {
    id: "Desktop-Plus",
    click: "addCharacter",
    lowerValue: "=",
    lowerRender: "=",
    upperValue: "+",
    UpperRender: "+",
  },
  {
    id: "Desktop-Q",
    click: "addCharacter",
    lowerValue: "q",
    lowerRender: "q",
    upperValue: "Q",
    UpperRender: "Q",
  },
  {
    id: "Desktop-W",
    click: "addCharacter",
    lowerValue: "w",
    lowerRender: "w",
    upperValue: "W",
    UpperRender: "W",
  },
  {
    id: "Desktop-E",
    click: "addCharacter",
    lowerValue: "e",
    lowerRender: "e",
    upperValue: "E",
    UpperRender: "E",
  },
  {
    id: "Desktop-R",
    click: "addCharacter",
    lowerValue: "r",
    lowerRender: "r",
    upperValue: "R",
    UpperRender: "R",
  },
  {
    id: "Desktop-T",
    click: "addCharacter",
    lowerValue: "t",
    lowerRender: "t",
    upperValue: "T",
    UpperRender: "T",
  },
  {
    id: "Desktop-Y",
    click: "addCharacter",
    lowerValue: "y",
    lowerRender: "y",
    upperValue: "Y",
    UpperRender: "Y",
  },
  {
    id: "Desktop-U",
    click: "addCharacter",
    lowerValue: "u",
    lowerRender: "u",
    upperValue: "U",
    UpperRender: "U",
  },
  {
    id: "Desktop-I",
    click: "addCharacter",
    lowerValue: "i",
    lowerRender: "i",
    upperValue: "I",
    UpperRender: "I",
  },
  {
    id: "Desktop-O",
    click: "addCharacter",
    lowerValue: "o",
    lowerRender: "o",
    upperValue: "O",
    UpperRender: "O",
  },
  {
    id: "Desktop-P",
    click: "addCharacter",
    lowerValue: "p",
    lowerRender: "p",
    upperValue: "P",
    UpperRender: "P",
  },
  {
    id: "Desktop-A",
    click: "addCharacter",
    lowerValue: "a",
    lowerRender: "a",
    upperValue: "A",
    UpperRender: "A",
  },
  {
    id: "Desktop-S",
    click: "addCharacter",
    lowerValue: "s",
    lowerRender: "s",
    upperValue: "S",
    UpperRender: "S",
  },
  {
    id: "Desktop-D",
    click: "addCharacter",
    lowerValue: "d",
    lowerRender: "d",
    upperValue: "D",
    UpperRender: "D",
  },
  {
    id: "Desktop-F",
    click: "addCharacter",
    lowerValue: "f",
    lowerRender: "f",
    upperValue: "F",
    UpperRender: "F",
  },
  {
    id: "Desktop-G",
    click: "addCharacter",
    lowerValue: "g",
    lowerRender: "g",
    upperValue: "G",
    UpperRender: "G",
  },
  {
    id: "Desktop-H",
    click: "addCharacter",
    lowerValue: "h",
    lowerRender: "h",
    upperValue: "H",
    UpperRender: "H",
  },
  {
    id: "Desktop-J",
    click: "addCharacter",
    lowerValue: "j",
    lowerRender: "j",
    upperValue: "J",
    UpperRender: "J",
  },
  {
    id: "Desktop-K",
    click: "addCharacter",
    lowerValue: "k",
    lowerRender: "k",
    upperValue: "K",
    UpperRender: "K",
  },
  {
    id: "Desktop-L",
    click: "addCharacter",
    lowerValue: "l",
    lowerRender: "l",
    upperValue: "L",
    UpperRender: "L",
  },
  {
    id: "Desktop-Semi-colon",
    click: "addCharacter",
    lowerValue: ";",
    lowerRender: ";",
    upperValue: ":",
    UpperRender: ":",
  },
  {
    id: "Desktop-Single-quote",
    click: "addCharacter",
    lowerValue: "'",
    lowerRender: "'",
    upperValue: "@",
    UpperRender: "@",
  },
  {
    id: "Desktop-Hash",
    click: "addCharacter",
    lowerValue: "#",
    lowerRender: "#",
    upperValue: "~",
    UpperRender: "~ ",
  },
  {
    id: "Desktop-Capital",
    click: "capitalize",
    lowerRender: (
      <FontAwesomeIcon className="icon" size={iconSize} icon={faAngleUp} />
    ),
    UpperRender: (
      <FontAwesomeIcon className="icon" size={iconSize} icon={faAngleDown} />
    ),
  },
  {
    id: "Desktop-Z",
    click: "addCharacter",
    lowerValue: "z",
    lowerRender: "z",
    upperValue: "Z",
    UpperRender: "Z",
  },
  {
    id: "Desktop-X",
    click: "addCharacter",
    lowerValue: "x",
    lowerRender: "x",
    upperValue: "X",
    UpperRender: "X",
  },
  {
    id: "Desktop-C",
    click: "addCharacter",
    lowerValue: "c",
    lowerRender: "c",
    upperValue: "C",
    UpperRender: "C",
  },
  {
    id: "Desktop-V",
    click: "addCharacter",
    lowerValue: "v",
    lowerRender: "v",
    upperValue: "V",
    UpperRender: "V",
  },
  {
    id: "Desktop-B",
    click: "addCharacter",
    lowerValue: "b",
    lowerRender: "b",
    upperValue: "B",
    UpperRender: "B",
  },
  {
    id: "Desktop-N",
    click: "addCharacter",
    lowerValue: "n",
    lowerRender: "n",
    upperValue: "N",
    UpperRender: "N",
  },
  {
    id: "Desktop-M",
    click: "addCharacter",
    lowerValue: "m",
    lowerRender: "m",
    upperValue: "M",
    UpperRender: "M",
  },
  {
    id: "Desktop-Comma",
    click: "addCharacter",
    lowerValue: ",",
    lowerRender: ",",
    upperValue: "<",
    UpperRender: "<",
  },
  {
    id: "Desktop-Dot",
    click: "addCharacter",
    lowerValue: ".",
    lowerRender: ".",
    upperValue: ">",
    UpperRender: ">",
  },
  {
    id: "Desktop-Back-slash",
    click: "addCharacter",
    lowerValue: "/",
    lowerRender: "/",
    upperValue: "?",
    UpperRender: "?",
  },
  {
    id: "Desktop-Delete",
    click: "removeCharacter",
    text: (
      <FontAwesomeIcon className="icon" size={iconSize} icon={faDeleteLeft} />
    ),
  },
  {
    id: "Desktop-Space",
    lowerValue: " ",
    upperValue: " ",
    click: "addCharacter",
    text: "Space",
  },
];
